apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: myvol
        mountPath: /etc/xyz_data
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: pvc2
