apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - image: nginx
    name: pod1
    env:
    - name: sys-password
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: sys-password
